# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Robert Ryan
tagline:          'Fix it, Build it, Learn it'
description:      'A place to write up my projects. <a href="https://twitter.com/rpryan" target="_blank">@rpryan</a>.'
url:              http://log.rpryan.org
baseurl:          /

author:
  name:           'Robert Ryan'
  url:            https://log.rpryan.org

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/robryanvt
